language: python
python:
  - "2.7"
# command to install dependencies
install:
  #- pip install nose opencv-python
  - pip install django selenium

env:
  - MOZ_HEADLESS=1

addons:
  - firefox: lastest

before_install:
  - wget https://github.com/mozilla/geckodriver/releases/download/v0.20.0/geckodriver-v0.20.0-linux64.tar.gz
  - mkdir geckodriver
  - tar -xzf geckodriver-v0.20.0-linux64.tar.gz -C geckodriver
  - export PATH=$PATH:$PWD/geckodriver
# command to run tests
script:
  #- "nosetests -v --with-xunit --with-coverage --cover-package=python --cover-inclusive --all-modules python/tests/"
  - "cd charades && python manage.py test -p test_wait*.py"
